baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'TJ d√©rives'
theme = 'archie'

[params]
        mode="toggle"
        subtitle = "wrangling on the edges of my map"
        customcss = ["css/tweak.css"]

[services]
        [services.disqus]
                shortname = 'dergumwong'

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/4096void"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/thrilling_gem"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Gems"
url = "/gems"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4